Header issue fixed
beeman/solana-next-v2 pull request #1
Opened 2024-12-30 15:41 UTC by Afoxcute

2024-12-30 16:20 UTC, beeman requested changes
Thanks @Afoxcute, this looks good! I left a few code comments on the PR.

Also, it looks like the menu now floats in the middle of the header on larger viewports.

![image](https://github.com/user-attachments/assets/96a2bb1b-bbe9-489c-9df7-8143684eacb2)

2024-12-30 16:20 UTC, beeman commented on yarn.lock
Please get rid of the yarn.lock file, the example uses pnpm.

2024-12-30 16:20 UTC, beeman commented on package.json
> +    "ws": "^8.18.0"
Let's remove the `tailwindcss-animate` and `ws` deps. We try to keep the dependencies of these templates to a minimum.

2024-12-30 16:20 UTC, beeman commented on src/components/app-layout.tsx
> -            {/*  <AccountChecker />*/}
Please don't remove unrelated code, this is an actual placeholder I'll add back in.

2024-12-30 19:32 UTC, Afoxcute commented
@beeman i have done it

2024-12-30 19:45 UTC, beeman commented
> @beeman i have done it

Thanks! I see that the `ws` dependency is still there https://github.com/solana-templates/solana-v2-next-shadcn/pull/1#discussion_r1899652846

This is how the header looks, please make it behave like it used to.
![image](https://github.com/user-attachments/assets/2f0d5b18-40cd-4733-a764-cf3848f8bfbe)


For reference, this is the current nav bar, taking the full width and with the navigation links on the right.
![image](https://github.com/user-attachments/assets/fe9dc382-1997-488e-baba-29c37e2427c1)

2025-01-01 13:52 UTC, Afoxcute commented
@beeman

2025-01-02 20:53 UTC, merged

2025-01-02 20:53 UTC, beeman commented
Thanks a lot @Afoxcute!

2025-01-02 20:57 UTC, Afoxcute commented
you are welcome. looking forward to participate in future issues.